[package]
name = "pipec"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.28"
crossterm = { version = "0.28", features = ["event-stream"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3.31"
tui-input = "0.10"